/* eslint-disable @typescript-eslint/no-unused-vars */
import { useMemo } from 'react';

export const Component = () => {
  // let use memo infer the type returned
  const autoGeneratedIds = useMemo(() => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);
};
